# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "nuget"
    directories:
      - "/Bat.Shared"
      - "/Bat.Shared.EF"
      - "/Bat.Api"
      - "/Bat.Blazor/Bat.Blazor"
      - "/Bat.Blazor/Bat.Blazor.App"
      - "/Bat.Blazor/Bat.Blazor.Client"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] # do not update to major version as it may contain breaking changes
