name: 'ci'

on:
  push:
    branches: [ '*' ]
  pull_request:
    types: [ opened, edited, reopened, synchronize, review_requested ]
    branches: [ '*' ]
  workflow_call:

env:
  TAG_PREFIX: v

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '8.x', '9.x' ]
    name: Build and test with dotnet ${{ matrix.dotnet }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup dotnet ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore
      # - name: Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}

  ReleaseDryRun:
    if: github.event_name == 'push'
    needs: BuildAndTest
    runs-on: ubuntu-latest
    outputs:
      RESULT: ${{ steps.release_dry_run.outputs.result }}
      VERSION: ${{ steps.release_dry_run.outputs.releaseVersion }}
      RELEASE_NOTES: ${{ steps.release_dry_run.outputs.releaseNotes }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
      - name: Release (dry-run)
        # see https://github.com/btnguyen2k/action-semrelease for documentation
        id: release_dry_run
        uses: btnguyen2k/action-semrelease@v4
        with:
          dry-run: true
          auto-mode: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-major-release: false
          tag-minor-release: false
          branches: ${{ github.ref_name }}
          tag-prefix: ${{ env.TAG_PREFIX }}
          tag-only: true

  TestDockerfileLinux:
    needs: BuildAndTest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms: [ 'linux/amd64', 'linux/arm64' ]
        dockerfiles: [ 'Dockerfile', 'Dockerfile.dev' ]
    name: Test building Docker image(s) for Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{ matrix.platforms }} with ${{ matrix.dockerfiles }}
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platforms }}
          push: false
          load: true
          tags: test
          file: ./${{ matrix.dockerfiles }}
          context: ./
      - name: Test Docker container for ${{ matrix.platforms }} with ${{ matrix.dockerfiles }}
        run: |
          CONTAINER=$(docker run -d \
            --name test \
            -p 1234:8080 \
            --platform ${{ matrix.platforms }} \
            test)
          sleep 30 # Wait for the container to start and bootstrap, increase wait time if needed
          docker logs ${CONTAINER}
          STATUS_OUTPUT=$(curl http://localhost:1234/healthz)
          echo "ℹ️ Health check output: $STATUS_OUTPUT"
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:1234/healthz)
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "❌ Health check failed with status code $STATUS_CODE"
            exit 1
          fi

  TestDockerfileWindows:
    needs: BuildAndTest
    runs-on: windows-2022
    strategy:
      matrix:
        platforms: [ 'windows/amd64' ]
    name: Test building Docker image(s) for Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build Docker image for ${{ matrix.platforms }}
        # Use mr-smithers-excellent/docker-build-push as docker/build-push-action requires docker/setup-buildx-action which does not support Windows yet
        # Monitor this issue https://github.com/docker/build-push-action/issues/18
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          platform: ${{ matrix.platforms }}
          registry: docker.io
          image: test
          tags: test
          pushImage: false
          dockerfile: ./Dockerfile.win
          directory: ./
